import type { Translations } from "@/types";

const translations: Translations = {
  ar: {
    nav: { home: "الرئيسية", inbox: "صندوق الوارد", faq: "الأسئلة الشائعة", contact: "اتصل بنا", privacy: "سياسة الخصوصية", terms: "شروط الخدمة" },
    hero: { title: "بريد عربي مؤقت", subtitle: "أنشئ بريداً إلكترونياً وهمياً فورياً لاستقبال رسائل التفعيل والتسجيلات بدون الكشف عن بريدك الحقيقي", createEmail: "إنشاء بريد وهمي", generating: "جارٍ الإنشاء..." },
    inbox: { title: "صندوق الوارد", empty: "لا توجد رسائل", emptyDesc: "انتظر وصول الرسائل... سيتم التحديث تلقائياً", newMessages: "رسائل جديدة", refresh: "تحديث", copy: "نسخ", copied: "تم النسخ!", delete: "حذف", newEmail: "بريد جديد", expiresIn: "ينتهي خلال", sender: "المرسل", subject: "العنوان", date: "التاريخ", noSubject: "بدون عنوان", noSender: "مرسل غير معروف", messageDetail: "تفاصيل الرسالة", close: "إغلاق", markRead: "تحديد كمقروء", deleteMessage: "حذف الرسالة", loading: "جاري التحميل...", verifyingLinks: "روابط التفعيل", clickToVerify: "اضغط للتفعيل", emailCopied: "تم نسخ البريد" },
    faq: { title: "الأسئلة الشائعة", items: [{ q: "ما هي خدمة مؤقت؟", a: "مؤقت هي خدمة بريد إلكتروني مؤقت تتيح لك إنشاء بريد وهمي لاستقبال الرسائل ورسائل التفعيل دون الحاجة للتسجيل أو كشف بريدك الشخصي." }, { q: "هل البريد مجاني؟", a: "نعم، الخدمة مجانية بالكامل ولا تتطلب أي تسجيل أو دفع." }, { q: "كم مدة صلاحية البريد؟", a: "صلاحية البريد هي 10 دقائق. يمكنك إنشاء بريد جديد في أي وقت." }, { q: "هل يمكنني الرد على الرسائل؟", a: "لا، هذه الخدمة مخصصة لاستقبال الرسائل فقط ولا تدعم إرسال الردود." }, { q: "هل بريدي آمن؟", a: "بريدك مؤقت ومجهول. لا نقوم بتخزين أي بيانات شخصية ويتم حذف البريد تلقائياً بعد انتهاء الصلاحية." }, { q: "ماذا لو انتهت صلاحية بريدي؟", a: "سيتم حذف البريد تلقائياً وجميع رسائله. يمكنك إنشاء بريد جديد بضغطة زر." }, { q: "هل تدعمون رسائل التفعيل؟", a: "نعم، تدعم الخدمة استقبال رسائل التفعيل من جميع المواقع والخدمات." }] },
    contact: { title: "اتصل بنا", name: "الاسم", email: "البريد الإلكتروني", message: "الرسالة", send: "إرسال", success: "تم إرسال رسالتك بنجاح!", error: "حدث خطأ أثناء الإرسال. حاول مرة أخرى." },
    footer: { description: "مؤقت — خدمة بريد إلكتروني عربي مؤقت سريعة وحديثة لإنشاء إيميلات وهمية واستقبال الرسائل بسهولة.", quickLinks: "روابط سريعة", legal: "قانوني", rights: "جميع الحقوق محفوظة." },
    theme: { light: "فاتح", dark: "داكن" },
    errors: { rateLimited: "طلبات كثيرة جداً. حاول بعد قليل.", serverError: "خطأ في الخادم. حاول مرة أخرى.", networkError: "خطأ في الشبكة. تحقق من اتصالك.", tryAgain: "حاول مرة أخرى" },
    seo: { title: "مؤقت | بريد إلكتروني مؤقت وهمي", description: "مؤقت — خدمة بريد إلكتروني مؤقت مجانية لإنشاء إيميلات وهمية واستقبال رسائل التفعيل والتسجيلات بسهولة وأمان.", keywords: "بريد مؤقت, بريد وهمي, إيميل مؤقت, temp mail, رسائل تفعيل" }
  },
  en: {
    nav: { home: "Home", inbox: "Inbox", faq: "FAQ", contact: "Contact", privacy: "Privacy Policy", terms: "Terms of Service" },
    hero: { title: "Instant Temporary Email", subtitle: "Create a disposable email instantly to receive activation emails and signups without revealing your real address.", createEmail: "Generate Temp Email", generating: "Generating..." },
    inbox: { title: "Inbox", empty: "No messages yet", emptyDesc: "Waiting for incoming messages... Auto-refreshes every 10 seconds", newMessages: "new messages", refresh: "Refresh", copy: "Copy", copied: "Copied!", delete: "Delete", newEmail: "New Email", expiresIn: "Expires in", sender: "From", subject: "Subject", date: "Date", noSubject: "No Subject", noSender: "Unknown Sender", messageDetail: "Message Detail", close: "Close", markRead: "Mark as Read", deleteMessage: "Delete Message", loading: "Loading...", verifyingLinks: "Verification Links", clickToVerify: "Click to Verify", emailCopied: "Email copied!" },
    faq: { title: "Frequently Asked Questions", items: [{ q: "What is Muaqt?", a: "Muaqt is a temporary email service that lets you create disposable email addresses to receive messages and activation emails without registration or revealing your personal email." }, { q: "Is it free?", a: "Yes, completely free. No registration or payment required." }, { q: "How long does the email last?", a: "The email address is valid for 10 minutes. You can create a new one anytime." }, { q: "Can I reply to messages?", a: "No, this service is for receiving messages only and does not support sending replies." }, { q: "Is my email secure?", a: "Your email is temporary and anonymous. We don't store any personal data and emails are automatically deleted after expiration." }, { q: "What happens when my email expires?", a: "The email and all its messages are automatically deleted. You can create a new one with one click." }, { q: "Do you support activation emails?", a: "Yes, the service supports receiving activation emails from all websites and services." }] },
    contact: { title: "Contact Us", name: "Name", email: "Email", message: "Message", send: "Send", success: "Your message has been sent successfully!", error: "An error occurred. Please try again." },
    footer: { description: "Muaqt — A fast and modern temporary email service for creating disposable addresses and receiving messages easily.", quickLinks: "Quick Links", legal: "Legal", rights: "All rights reserved." },
    theme: { light: "Light", dark: "Dark" },
    errors: { rateLimited: "Too many requests. Please try again later.", serverError: "Server error. Please try again.", networkError: "Network error. Check your connection.", tryAgain: "Try Again" },
    seo: { title: "Muaqt | Temporary Disposable Email Service", description: "Muaqt — Free temporary email service. Create disposable email addresses instantly to receive activation emails and registrations safely.", keywords: "temp mail, temporary email, disposable email, fake email, temporary email address" }
  },
  fr: {
    nav: { home: "Accueil", inbox: "Boîte de réception", faq: "FAQ", contact: "Contact", privacy: "Confidentialité", terms: "Conditions d'utilisation" },
    hero: { title: "Email Temporaire Instantané", subtitle: "Créez un email jetable instantanément pour recevoir des emails d'activation sans révéler votre adresse réelle.", createEmail: "Générer un Email Temporaire", generating: "Génération..." },
    inbox: { title: "Boîte de réception", empty: "Aucun message", emptyDesc: "En attente de messages... Actualisation automatique", newMessages: "nouveaux messages", refresh: "Actualiser", copy: "Copier", copied: "Copié !", delete: "Supprimer", newEmail: "Nouvel Email", expiresIn: "Expire dans", sender: "Expéditeur", subject: "Sujet", date: "Date", noSubject: "Sans objet", noSender: "Expéditeur inconnu", messageDetail: "Détail du message", close: "Fermer", markRead: "Marquer comme lu", deleteMessage: "Supprimer le message", loading: "Chargement...", verifyingLinks: "Liens de vérification", clickToVerify: "Cliquer pour vérifier", emailCopied: "Email copié !" },
    faq: { title: "Questions Fréquentes", items: [{ q: "Qu'est-ce que Muaqt ?", a: "Muaqt est un service d'email temporaire qui vous permet de créer des adresses jetables pour recevoir des messages sans inscription." }, { q: "Est-ce gratuit ?", a: "Oui, entièrement gratuit. Aucune inscription ni paiement requis." }, { q: "Combien de temps dure l'email ?", a: "L'adresse email est valable 10 minutes. Vous pouvez en créer une nouvelle à tout moment." }, { q: "Puis-je répondre aux messages ?", a: "Non, ce service est uniquement destiné à la réception de messages." }, { q: "Mon email est-il sécurisé ?", a: "Votre email est temporaire et anonyme. Nous ne stockons aucune donnée personnelle." }, { q: "Que se passe-t-il quand mon email expire ?", a: "L'email et tous ses messages sont automatiquement supprimés." }, { q: "Supportez-vous les emails d'activation ?", a: "Oui, le service prend en charge la réception d'emails d'activation de tous les sites." }] },
    contact: { title: "Contactez-nous", name: "Nom", email: "Email", message: "Message", send: "Envoyer", success: "Votre message a été envoyé avec succès !", error: "Une erreur s'est produite. Veuillez réessayer." },
    footer: { description: "Muaqt — Un service d'email temporaire rapide et moderne.", quickLinks: "Liens rapides", legal: "Juridique", rights: "Tous droits réservés." },
    theme: { light: "Clair", dark: "Sombre" },
    errors: { rateLimited: "Trop de requêtes. Réessayez plus tard.", serverError: "Erreur serveur. Réessayez.", networkError: "Erreur réseau. Vérifiez votre connexion.", tryAgain: "Réessayer" },
    seo: { title: "Muaqt | Service d'Email Temporaire Jetable", description: "Muaqt — Service d'email temporaire gratuit. Créez des adresses email jetables instantanément.", keywords: "email temporaire, email jetable, email poubelle, adresse email temporaire" }
  },
  es: {
    nav: { home: "Inicio", inbox: "Bandeja de entrada", faq: "FAQ", contact: "Contacto", privacy: "Privacidad", terms: "Términos" },
    hero: { title: "Email Temporal Instantáneo", subtitle: "Crea un email desechable al instante para recibir correos de activación sin revelar tu dirección real.", createEmail: "Generar Email Temporal", generating: "Generando..." },
    inbox: { title: "Bandeja de entrada", empty: "Sin mensajes", emptyDesc: "Esperando mensajes... Actualización automática", newMessages: "mensajes nuevos", refresh: "Actualizar", copy: "Copiar", copied: "¡Copiado!", delete: "Eliminar", newEmail: "Nuevo Email", expiresIn: "Expira en", sender: "Remitente", subject: "Asunto", date: "Fecha", noSubject: "Sin asunto", noSender: "Remitente desconocido", messageDetail: "Detalle del mensaje", close: "Cerrar", markRead: "Marcar como leído", deleteMessage: "Eliminar mensaje", loading: "Cargando...", verifyingLinks: "Enlaces de verificación", clickToVerify: "Haga clic para verificar", emailCopied: "¡Email copiado!" },
    faq: { title: "Preguntas Frecuentes", items: [{ q: "¿Qué es Muaqt?", a: "Muaqt es un servicio de email temporal que permite crear direcciones desechables para recibir mensajes sin registro." }, { q: "¿Es gratis?", a: "Sí, completamente gratis. Sin registro ni pago." }, { q: "¿Cuánto dura el email?", a: "La dirección es válida por 10 minutos. Puede crear una nueva en cualquier momento." }, { q: "¿Puedo responder mensajes?", a: "No, este servicio es solo para recibir mensajes." }, { q: "¿Es seguro mi email?", a: "Su email es temporal y anónimo. No almacenamos datos personales." }, { q: "¿Qué pasa cuando expira?", a: "El email y todos los mensajes se eliminan automáticamente." }, { q: "¿Soportan correos de activación?", a: "Sí, el servicio soporta la recepción de correos de activación." }] },
    contact: { title: "Contáctenos", name: "Nombre", email: "Email", message: "Mensaje", send: "Enviar", success: "¡Mensaje enviado con éxito!", error: "Ocurrió un error. Intente de nuevo." },
    footer: { description: "Muaqt — Un servicio de email temporal rápido y moderno.", quickLinks: "Enlaces rápidos", legal: "Legal", rights: "Todos los derechos reservados." },
    theme: { light: "Claro", dark: "Oscuro" },
    errors: { rateLimited: "Demasiadas solicitudes. Intente más tarde.", serverError: "Error del servidor. Intente de nuevo.", networkError: "Error de red. Verifique su conexión.", tryAgain: "Intentar de nuevo" },
    seo: { title: "Muaqt | Servicio de Email Temporal Desechable", description: "Muaqt — Servicio de email temporal gratuito. Cree direcciones de email desechables al instante.", keywords: "email temporal, email desechable, email falso, temp mail" }
  },
  de: {
    nav: { home: "Start", inbox: "Posteingang", faq: "FAQ", contact: "Kontakt", privacy: "Datenschutz", terms: "AGB" },
    hero: { title: "Sofortige Wegwerf-E-Mail", subtitle: "Erstellen Sie sofort eine Wegwerf-E-Mail-Adresse, um Aktivierungs-E-Mails zu empfangen, ohne Ihre echte Adresse preiszugeben.", createEmail: "Temp-E-Mail generieren", generating: "Generiere..." },
    inbox: { title: "Posteingang", empty: "Keine Nachrichten", emptyDesc: "Warte auf eingehende Nachrichten... Automatische Aktualisierung", newMessages: "neue Nachrichten", refresh: "Aktualisieren", copy: "Kopieren", copied: "Kopiert!", delete: "Löschen", newEmail: "Neue E-Mail", expiresIn: "Läuft ab in", sender: "Absender", subject: "Betreff", date: "Datum", noSubject: "Kein Betreff", noSender: "Unbekannter Absender", messageDetail: "Nachrichtendetail", close: "Schließen", markRead: "Als gelesen markieren", deleteMessage: "Nachricht löschen", loading: "Laden...", verifyingLinks: "Bestätigungslinks", clickToVerify: "Klicken zum Bestätigen", emailCopied: "E-Mail kopiert!" },
    faq: { title: "Häufig gestellte Fragen", items: [{ q: "Was ist Muaqt?", a: "Muaqt ist ein temporärer E-Mail-Dienst, mit dem Sie Wegwerf-E-Mail-Adressen erstellen können." }, { q: "Ist es kostenlos?", a: "Ja, völlig kostenlos. Keine Registrierung oder Zahlung erforderlich." }, { q: "Wie lange hält die E-Mail?", a: "Die Adresse ist 10 Minuten gültig. Sie können jederzeit eine neue erstellen." }, { q: "Kann ich auf Nachrichten antworten?", a: "Nein, dieser Dienst dient nur zum Empfangen von Nachrichten." }, { q: "Ist meine E-Mail sicher?", a: "Ihre E-Mail ist temporär und anonym. Wir speichern keine persönlichen Daten." }, { q: "Was passiert wenn meine E-Mail abläuft?", a: "Die E-Mail und alle Nachrichten werden automatisch gelöscht." }, { q: "Unterstützen Sie Aktivierungs-E-Mails?", a: "Ja, der Dienst unterstützt den Empfang von Aktivierungs-E-Mails." }] },
    contact: { title: "Kontaktieren Sie uns", name: "Name", email: "E-Mail", message: "Nachricht", send: "Senden", success: "Ihre Nachricht wurde erfolgreich gesendet!", error: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut." },
    footer: { description: "Muaqt — Ein schneller und moderner temporärer E-Mail-Dienst.", quickLinks: "Schnelllinks", legal: "Rechtliches", rights: "Alle Rechte vorbehalten." },
    theme: { light: "Hell", dark: "Dunkel" },
    errors: { rateLimited: "Zu viele Anfragen. Versuchen Sie es später erneut.", serverError: "Serverfehler. Bitte versuchen Sie es erneut.", networkError: "Netzwerkfehler. Überprüfen Sie Ihre Verbindung.", tryAgain: "Erneut versuchen" },
    seo: { title: "Muaqt | Temporärer Wegwerf-E-Mail-Dienst", description: "Muaqt — Kostenloser temporärer E-Mail-Dienst. Erstellen Sie sofort Wegwerf-E-Mail-Adressen.", keywords: "temp mail, wegwerf email, temporäre email, fake email" }
  },
  tr: {
    nav: { home: "Ana Sayfa", inbox: "Gelen Kutusu", faq: "SSS", contact: "İletişim", privacy: "Gizlilik", terms: "Şartlar" },
    hero: { title: "Anlık Geçici E-posta", subtitle: "Gerçek adresinizi vermeden aktivasyon e-postaları almak için anında geçici bir e-posta oluşturun.", createEmail: "Geçici E-posta Oluştur", generating: "Oluşturuluyor..." },
    inbox: { title: "Gelen Kutusu", empty: "Henüz mesaj yok", emptyDesc: "Gelen mesajlar bekleniyor... Otomatik yenileniyor", newMessages: "yeni mesaj", refresh: "Yenile", copy: "Kopyala", copied: "Kopyalandı!", delete: "Sil", newEmail: "Yeni E-posta", expiresIn: "Son kullanma", sender: "Gönderen", subject: "Konu", date: "Tarih", noSubject: "Konusuz", noSender: "Bilinmeyen Gönderen", messageDetail: "Mesaj Detayı", close: "Kapat", markRead: "Okundu olarak işaretle", deleteMessage: "Mesajı Sil", loading: "Yükleniyor...", verifyingLinks: "Doğrulama Bağlantıları", clickToVerify: "Doğrulamak için tıkla", emailCopied: "E-posta kopyalandı!" },
    faq: { title: "Sıkça Sorulan Sorular", items: [{ q: "Muaqt nedir?", a: "Muaqt, kayıt olmadan mesaj almak için geçici e-posta adresleri oluşturmanızı sağlayan bir hizmettir." }, { q: "Ücretsiz mi?", a: "Evet, tamamen ücretsiz. Kayıt veya ödeme gerekmez." }, { q: "E-posta ne kadar süre geçerli?", a: "E-posta adresi 10 dakika geçerlidir. İstediğiniz zaman yenisini oluşturabilirsiniz." }, { q: "Mesajlara yanıt verebilir miyim?", a: "Hayır, bu hizmet yalnızca mesaj almak içindir." }, { q: "E-postam güvende mi?", a: "E-postanız geçici ve anonimdir. Hiçbir kişisel veri saklamıyoruz." }, { q: "E-postam süresi dolunca ne olur?", a: "E-posta ve tüm mesajları otomatik olarak silinir." }, { q: "Aktivasyon e-postalarını destekliyor musunuz?", a: "Evet, tüm sitelerden aktivasyon e-postaları almayı destekler." }] },
    contact: { title: "İletişim", name: "Ad", email: "E-posta", message: "Mesaj", send: "Gönder", success: "Mesajınız başarıyla gönderildi!", error: "Bir hata oluştu. Lütfen tekrar deneyin." },
    footer: { description: "Muaqt — Hızlı ve modern geçici e-posta hizmeti.", quickLinks: "Hızlı Linkler", legal: "Yasal", rights: "Tüm hakları saklıdır." },
    theme: { light: "Aydınlık", dark: "Karanlık" },
    errors: { rateLimited: "Çok fazla istek. Lütfen daha sonra tekrar deneyin.", serverError: "Sunucu hatası. Lütfen tekrar deneyin.", networkError: "Ağ hatası. Bağlantınızı kontrol edin.", tryAgain: "Tekrar Dene" },
    seo: { title: "Muaqt | Geçici E-posta Hizmeti", description: "Muaqt — Ücretsiz geçici e-posta hizmeti. Anında geçici e-posta adresleri oluşturun.", keywords: "geçici mail, temp mail, tek kullanımlık email, sahte email" }
  },
  ru: {
    nav: { home: "Главная", inbox: "Входящие", faq: "FAQ", contact: "Контакты", privacy: "Конфиденциальность", terms: "Условия" },
    hero: { title: "Мгновенная Временная Почта", subtitle: "Создайте одноразовый email мгновенно для получения писем активации без раскрытия вашего реального адреса.", createEmail: "Создать Временный Email", generating: "Создание..." },
    inbox: { title: "Входящие", empty: "Нет сообщений", emptyDesc: "Ожидание сообщений... Автообновление", newMessages: "новых сообщений", refresh: "Обновить", copy: "Копировать", copied: "Скопировано!", delete: "Удалить", newEmail: "Новый Email", expiresIn: "Истекает через", sender: "Отправитель", subject: "Тема", date: "Дата", noSubject: "Без темы", noSender: "Неизвестный отправитель", messageDetail: "Детали сообщения", close: "Закрыть", markRead: "Отметить прочитанным", deleteMessage: "Удалить сообщение", loading: "Загрузка...", verifyingLinks: "Ссылки для подтверждения", clickToVerify: "Нажмите для подтверждения", emailCopied: "Email скопирован!" },
    faq: { title: "Часто задаваемые вопросы", items: [{ q: "Что такое Muaqt?", a: "Muaqt — это сервис временной электронной почты, позволяющий создавать одноразовые адреса для получения сообщений." }, { q: "Это бесплатно?", a: "Да, полностью бесплатно. Никакой регистрации или оплаты." }, { q: "Как долго действует email?", a: "Адрес действует 10 минут. Вы можете создать новый в любое время." }, { q: "Могу ли я отвечать на сообщения?", a: "Нет, этот сервис предназначен только для получения сообщений." }, { q: "Безопасен ли мой email?", a: "Ваш email временный и анонимный. Мы не храним личные данные." }, { q: "Что происходит когда email истекает?", a: "Email и все сообщения автоматически удаляются." }, { q: "Поддерживаете ли вы письма активации?", a: "Да, сервис поддерживает получение писем активации." }] },
    contact: { title: "Свяжитесь с нами", name: "Имя", email: "Email", message: "Сообщение", send: "Отправить", success: "Ваше сообщение отправлено!", error: "Произошла ошибка. Попробуйте снова." },
    footer: { description: "Muaqt — Быстрый и современный сервис временной почты.", quickLinks: "Быстрые ссылки", legal: "Юридическая информация", rights: "Все права защищены." },
    theme: { light: "Светлая", dark: "Тёмная" },
    errors: { rateLimited: "Слишком много запросов. Попробуйте позже.", serverError: "Ошибка сервера. Попробуйте снова.", networkError: "Ошибка сети. Проверьте подключение.", tryAgain: "Попробовать снова" },
    seo: { title: "Muaqt | Сервис Временной Почты", description: "Muaqt — Бесплатный сервис временной электронной почты. Создавайте одноразовые адреса мгновенно.", keywords: "временная почта, одноразовая почта, temp mail, фейковая почта" }
  },
  zh: {
    nav: { home: "首页", inbox: "收件箱", faq: "常见问题", contact: "联系我们", privacy: "隐私政策", terms: "服务条款" },
    hero: { title: "即时临时邮箱", subtitle: "立即创建一次性邮箱，接收激活邮件和注册确认，无需透露您的真实地址。", createEmail: "生成临时邮箱", generating: "生成中..." },
    inbox: { title: "收件箱", empty: "暂无邮件", emptyDesc: "等待 incoming 邮件... 每10秒自动刷新", newMessages: "封新邮件", refresh: "刷新", copy: "复制", copied: "已复制！", delete: "删除", newEmail: "新邮箱", expiresIn: "过期时间", sender: "发件人", subject: "主题", date: "日期", noSubject: "无主题", noSender: "未知发件人", messageDetail: "邮件详情", close: "关闭", markRead: "标记为已读", deleteMessage: "删除邮件", loading: "加载中...", verifyingLinks: "验证链接", clickToVerify: "点击验证", emailCopied: "邮箱已复制！" },
    faq: { title: "常见问题", items: [{ q: "什么是 Muaqt？", a: "Muaqt 是一个临时邮箱服务，让您可以创建一次性邮箱地址来接收邮件，无需注册。" }, { q: "免费吗？", a: "是的，完全免费。无需注册或付费。" }, { q: "邮箱有效期多长？", a: "邮箱地址有效期为10分钟。您可以随时创建新邮箱。" }, { q: "我可以回复邮件吗？", a: "不可以，本服务仅用于接收邮件。" }, { q: "我的邮箱安全吗？", a: "您的邮箱是临时和匿名的。我们不存储任何个人数据。" }, { q: "邮箱过期后会怎样？", a: "邮箱和所有邮件将自动删除。" }, { q: "支持激活邮件吗？", a: "是的，服务支持接收来自所有网站的激活邮件。" }] },
    contact: { title: "联系我们", name: "姓名", email: "邮箱", message: "留言", send: "发送", success: "您的消息已成功发送！", error: "发生错误，请重试。" },
    footer: { description: "Muaqt — 快速现代的临时邮箱服务。", quickLinks: "快速链接", legal: "法律信息", rights: "保留所有权利。" },
    theme: { light: "浅色", dark: "深色" },
    errors: { rateLimited: "请求过多，请稍后重试。", serverError: "服务器错误，请重试。", networkError: "网络错误，请检查连接。", tryAgain: "重试" },
    seo: { title: "Muaqt | 临时邮箱服务", description: "Muaqt — 免费临时邮箱服务。立即创建一次性邮箱地址。", keywords: "临时邮箱, 一次性邮箱, 临时邮件, 虚假邮箱" }
  },
  ja: {
    nav: { home: "ホーム", inbox: "受信トレイ", faq: "よくある質問", contact: "お問い合わせ", privacy: "プライバシー", terms: "利用規約" },
    hero: { title: "即時使い捨てメール", subtitle: "実際のアドレスを公開せずに、確認メールや登録メールを受信するための使い捨てメールを即座に作成します。", createEmail: "使い捨てメールを作成", generating: "生成中..." },
    inbox: { title: "受信トレイ", empty: "メッセージはまだありません", emptyDesc: "メッセージを待機中... 10秒ごとに自動更新", newMessages: "件の新着メッセージ", refresh: "更新", copy: "コピー", copied: "コピーしました！", delete: "削除", newEmail: "新しいメール", expiresIn: "期限切れまで", sender: "送信者", subject: "件名", date: "日付", noSubject: "件名なし", noSender: "不明な送信者", messageDetail: "メッセージ詳細", close: "閉じる", markRead: "既読にする", deleteMessage: "メッセージを削除", loading: "読み込み中...", verifyingLinks: "確認リンク", clickToVerify: "クリックして確認", emailCopied: "メールをコピーしました！" },
    faq: { title: "よくある質問", items: [{ q: "Muaqtとは？", a: "Muaqtは、登録なしでメッセージを受信するための使い捨てメールアドレスを作成できるサービスです。" }, { q: "無料ですか？", a: "はい、完全に無料です。登録や支払いは不要です。" }, { q: "メールの有効期限は？", a: "メールアドレスは10分間有効です。いつでも新しいものを作成できます。" }, { q: "メッセージに返信できますか？", a: "いいえ、このサービスはメッセージの受信のみを目的としています。" }, { q: "メールは安全ですか？", a: "メールは一時的で匿名です。個人データは一切保存しません。" }, { q: "メールが期限切れになるとどうなりますか？", a: "メールとすべてのメッセージは自動的に削除されます。" }, { q: "確認メールに対応していますか？", a: "はい、すべてのサイトからの確認メール受信に対応しています。" }] },
    contact: { title: "お問い合わせ", name: "お名前", email: "メール", message: "メッセージ", send: "送信", success: "メッセージは正常に送信されました！", error: "エラーが発生しました。もう一度お試しください。" },
    footer: { description: "Muaqt — 高速でモダンな使い捨てメールサービス。", quickLinks: "クイックリンク", legal: "法的情報", rights: "全著作権所有。" },
    theme: { light: "ライト", dark: "ダーク" },
    errors: { rateLimited: "リクエストが多すぎます。後でもう一度お試しください。", serverError: "サーバーエラー。もう一度お試しください。", networkError: "ネットワークエラー。接続を確認してください。", tryAgain: "再試行" },
    seo: { title: "Muaqt | 使い捨てメールサービス", description: "Muaqt — 無料の使い捨てメールサービス。即座に使い捨てメールアドレスを作成。", keywords: "使い捨てメール, 一時メール, 仮メール, temp mail" }
  }
};

export default translations;
